openapi: 3.0.3
info:
  title: Escape Game Jam API
  version: 1.0.0
  description: API for interacting with the Escape Game Jam NPC assistant.
servers:
  - url: https://escape-gamejam-worker.stepzepp.workers.dev/
paths:
  /chat:
    post:
      summary: Interact with the NPC assistant
      description: |
        Send the player's stats to the NPC assistant and receive a persuasive question and possible answers.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                boredom:
                  type: number
                  description: The player's boredom score.
                hunger:
                  type: number
                  description: The player's hunger score.
                toilet:
                  type: number
                  description: The player's toilet score.
              required:
                - boredom
                - hunger
                - toilet
      responses:
        '200':
          description: Successful response from the NPC assistant
          content:
            application/json:
              schema:
                type: object
                properties:
                  question:
                    type: string
                    description: NPC's persuasive question.
                  answers:
                    type: array
                    description: Possible answers for the user to choose from when replying to the question.
                    items:
                      type: object
                      properties:
                        type:
                          type: string
                          enum: [boredom, hunger, toilet]
                          description: The type of need affected by the answer.
                        text:
                          type: string
                          description: The answer text shown to the player.
                        points:
                          type: integer
                          minimum: -5
                          maximum: 5
                          description: Points to add or subtract based on the player's choice.
                      required:
                        - type
                        - text
                        - points
                      additionalProperties: false
                required:
                  - question
                  - answers
                  
        '400':
          description: Bad request (missing or invalid input)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '401':
          description: Unauthorized (missing or invalid API key)
          content:
            text/plain:
              schema:
                type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT 